sudo: false
language: node_js
node_js:
  - 13 
cache: npm
branches:
  only:
    - feat/1.0.0 # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    target_branch: master
  local-dir: public